[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Shapefile = "8e980c4a-a4fe-5da2-b3a7-4b4b0353a2f4"
PkgBenchmark = "32113eaa-f34f-5b0d-bd6c-c81e245fc73d"