name = "ArchGDAL"
uuid = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
keywords = ["GDAL", "IO"]
license = "MIT"
desc = "A high level API for GDAL - Geospatial Data Abstraction Library"
version = "0.7.4"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DiskArrays = "3c3547ce-8d99-4f5e-a174-61eb10b00ae3"
GDAL = "add2ef01-049f-52c4-9ee2-e494f65e021a"
GeneralizedGenerated = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
GeoFormatTypes = "68eda718-8dee-11e9-39e7-89f7f65f511f"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
RuntimeGeneratedFunctions = "7e49a35a-f44a-4d26-94aa-eba1b4ca6b47"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
CEnum = "0.4"
ColorTypes = "0.10, 0.11"
DiskArrays = "0.2.4"
GDAL = "1.1.3"
GeneralizedGenerated = "0.3"
GeoFormatTypes = "0.3"
GeoInterface = "0.4, 0.5"
ImageCore = "0.8, 0.9"
RuntimeGeneratedFunctions = "0.5"
Tables = "1"
julia = "1.3"
